[tool.ruff]
# Exclude a variety of commonly ignored directories.
exclude = [
    ".eggs",
    ".git",
    ".mypy_cache",
    ".pyenv"
]
include = ["*.py",]

line-length = 120
indent-width = 4
target-version = "py312"

lint.select = ["ALL"]
lint.ignore = ["D203", "D212", "ISC001", "COM812", "T201"]

# Allow fix for all enabled rules (when `--fix`) is provided.
lint.fixable = ["ALL"]
lint.unfixable = []
